version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      # Checkout code so that `find` can access your files
      - checkout
      - run:
          name: "Install findutils"
          command: |
            apt-get update && apt-get install -y findutils
      - run:
          name: "Inspect environment"
          command: |
            echo "Inspecting environment:"
            echo "Shell: $SHELL"
            echo "Environment Variables:"
            env
            echo "List of files in /usr/bin"
            ls /usr/bin
            echo "List of files in the current directory"
            find .  # Now find should work as it's installed

      - attach_workspace:
          at: ~/workspace

      # Running the SonarQube scanner with the configured parameters
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: " $SONAR_BRANCH
          echo "Sonar org value is : "$SONAR_ORG
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
