name: API Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install
        working-directory: PART-3/backend

      # Run individual API tests and store output
      - name: Run Login API Test
        id: login_test
        run: node PART-3/backend/test/testLogin.js

      - name: Run Create Payment API Test
        id: create_payment_test
        run: node PART-3/backend/test/testCreatePayment.js

      - name: Run My Payments API Test
        id: my_payments_test
        run: node PART-3/backend/test/testMyPayments.js

      - name: Run All Payments API Test
        id: all_payments_test
        run: node PART-3/backend/test/testAllPayments.js

      # Check if each test passed based on exit code
      - name: Check Login API Test Result
        if: steps.login_test.outcome == 'success'
        run: echo "Login API test passed successfully"

      - name: Check Create Payment API Test Result
        if: steps.create_payment_test.outcome == 'success'
        run: echo "Create Payment API test passed successfully"

      - name: Check My Payments API Test Result
        if: steps.my_payments_test.outcome == 'success'
        run: echo "My Payments API test passed successfully"

      - name: Check All Payments API Test Result
        if: steps.all_payments_test.outcome == 'success'
        run: echo "All Payments API test passed successfully"
